### ISSUE TITLE
Forecast results

### ISSUE THREAD

**Issue by urlhearts** [Zyun-Y/DconnNet#10]
Our number of class is 1, and the final predicted result is [1,8,320,320]. Which 8-dimensional feature should we choose as the predicted result

**Comment by Zyun-Y** [comment]
Hi,

This 8-channel output of the network is the connectivity map, not the segmentation map.

Please follow the line 204-208 in solver.py to input it into Bilateral_voting and the output pred will be your final segmentation prediction.




________________________________
From: urlhearts ***@***.***>
Sent: Tuesday, July 4, 2023 6:27:26 PM
To: Zyun-Y/DconnNet ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Zyun-Y/DconnNet] Forecast results (Issue #10)


Our number of class is 1, and the final predicted result is [1,8,320,320]. Which 8-dimensional feature should we choose as the predicted result
