### ISSUE TITLE
Is it possible to share the code of computing DSC_V and BACC

### ISSUE THREAD

**Issue by jamesben6688** [Zyun-Y/DconnNet#12]
Thank you so much for sharing your work. I observer that you only calculate the 2D dice score and jac score. Is it possible you share the code of computing DSC_v and BACC. Many thanks.

**Comment by Zyun-Y** [comment]
Hi, the only difference between image-wise and volume-wise DSC and BACC is the data you used. What you can do is to save the predicted images by volumes and use the same DSC code to compute the volume-wise DSC.

For BACC, it is (sensitivity + specificity)/2, which also can be generalized from the DSC code.
