### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by Kedaya66** [Zyun-Y/DconnNet#13]
Hello! Could you offer me a copy of the Retouch dataset?

**Comment by Zyun-Y** [comment]
Unfortunately we can’t. Please go to their official website to request the access.


________________________________
From: Kedaya66 ***@***.***>
Sent: Monday, August 14, 2023 6:49:57 AM
To: Zyun-Y/DconnNet ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Zyun-Y/DconnNet] Dataset request (Issue #13)


Hello! Could you offer me a copy of the Retouch dataset?

**Comment by Kedaya66** [comment]
Their website have closed the request. 
qaq

**Comment by Kedaya66** [comment]
I have another question. 
How to install apex in windows and ubuntu?
I have searched some tutorials, but none of them works...

**Comment by Zyun-Y** [comment]
Hi I believe you can go to the official GitHub site of [Apex](https://github.com/NVIDIA/apex).

If still not working, please just disregard the apex part in the codes.

**Comment by bigfishfour** [comment]
> Hello! Could you offer me a copy of the Retouch dataset?

Hello, may I ask if you have preprocessed the Retouch dataset and how to preprocess it？
