### ISSUE TITLE
question about the LWdecoder

### ISSUE THREAD

**Issue by Kedaya66** [Zyun-Y/DconnNet#14]
hello！
What is the structure of LWdecoder ？

**Comment by Kedaya66** [comment]
what is thr meaning of Bilateral Voting (BV) module in (11) and the Region-guided Channel Aggregation (RCA) module

**Comment by Zyun-Y** [comment]
Please read the paper to find all these information.


________________________________

**Comment by Zyun-Y** [comment]
For Bilateral Voting and RCA, they can be found in our BiconNet [Paper](https://github.com/Zyun-Y/BiconNets).

**Comment by Kedaya66** [comment]
Ok！Thanks
