### ISSUE TITLE
question about the distribution of retouch dataset

### ISSUE THREAD

**Issue by Kedaya66** [Zyun-Y/DconnNet#15]
assert 'retouch' in self.args.dataset, 'Please input the calculated distribution data of your own dataset, if you are now using Retouch'

Hello! I am writing to ask how to calculate the distribution of my own dataset. Could you take retouch as an example?

**Comment by Zyun-Y** [comment]
You can get your own distribution by:

1. Go through your entire dataset and calculate the pixel number for different classes.
2. Save the counting result in a matrix that has a shape of (C, N) where C is the class number, and N is the sample number.
