### ISSUE TITLE
Question about the calculation of betti number in DconnNet

### ISSUE THREAD

**Issue by WeiQijie** [Zyun-Y/DconnNet#17]
Hi, I am wondering why the betti numbers are calculated among 65*65 patches in metrics.cal_betti.getBetti(). Is it a common practice or from somewhere else. Thanks a lot

**Comment by Zyun-Y** [comment]
Hi, we followed the implementation of clDice paper and we believe it is a common practice to use patches for betti calculation.


________________________________
From: WeiQijie ***@***.***>
Sent: Monday, September 4, 2023 10:37:49 PM
To: Zyun-Y/DconnNet ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Zyun-Y/DconnNet] Question about the calculation of betti number in DconnNet (Issue #17)


Hi, I am wondering why the betti numbers are calculated among 65*65 patches in metrics.cal_betti.getBetti(). Is it a common practice or from somewhere else. Thanks a lot

**Comment by MonikaPandora** [comment]
Hi, I am wondering how to compute 0-Betti number for CHASEDB1. Does it means the only thing I need to do is to change 'i = 1' to 'i = 0' and leave the topo_size=65 unchanged? If so, why is the 0-Betty number computed relatively low?(even an order of magnitude lower)

**Comment by MonikaPandora** [comment]
I experimented and noticed that the patch size affects the results a lot, how can I find the commonly used setting?
