### ISSUE TITLE
Pretrained models and predictions for the CHASEDB1 dataset are missing in the shared link

### ISSUE THREAD

**Issue by Fivethousand5k** [Zyun-Y/DconnNet#2]
Hi, thanks for your inspiring work.  

I found the models and predictions for the CHASEDB1 were missing in the [link](https://drive.google.com/drive/folders/1xwg5J1P628vP1bcqL_d5uU-L-Vn8_A2f).

Could you please upload them？ Besides that, it would be better if you tell us how you split the CHASEDB1 dataset for 5-fold CV. Thanks!

**Comment by Zyun-Y** [comment]
Thank you for your interest. We will upload the predictions for CHASEDB1 very soon.

As for the sub-folds, please refer to line 119 in `train.py`

**Comment by Fivethousand5k** [comment]
Thanks, waiting for it.

**Comment by Zyun-Y** [comment]
Just uploaded
