### ISSUE TITLE
About the disentanglement of directional subspace

### ISSUE THREAD

**Issue by ZZhangyutong** [Zyun-Y/DconnNet#21]
In your paper which is related to this code, Figure 10 shows different results on T-SNE.
Pls, do you have any relevant code here about How to visualize the output of SDEs into 8 categories, I want to test it locally.
Thank you！

**Comment by Zyun-Y** [comment]
Hi, we grouped it after T-SNE.

**Comment by ZZhangyutong** [comment]
> Hi, we grouped it after T-SNE.

utilize K-means into 8 groups?

**Comment by Zyun-Y** [comment]
Yes.
