### ISSUE TITLE
How does Bilateral_voting work?

### ISSUE THREAD

**Issue by jzyxn** [Zyun-Y/DconnNet#22]
Hi author, in the Bilateral_voting function, I am confused by code like the following
    left =(torch.bmm(c_map[:,:,3].contiguous().view(-1,row,column),hori_translation.transpose(3,2).view(-1,column,column))).view(batch, class_num,row,column)
According to my current knowledge, I think it is calculating the part X_{9-j}(x+a,y+b) according to equation (11), may I ask the author what exactly it is doing, I hope the author can tell me (due to my weak code ability, I hope the author can be as detailed as possible). I would be grateful if the author could give me some advice.

**Comment by Zyun-Y** [comment]
Hi, you were right. This was used to shift the c_map to the different directions (left for here) with a matrix multiplication

**Comment by jzyxn** [comment]
Ok，thanks
