### ISSUE TITLE
The version of your python apex

### ISSUE THREAD

**Issue by OopsXie** [Zyun-Y/DconnNet#24]
I got a error
![1](https://github.com/Zyun-Y/DconnNet/assets/45565892/b75832a6-37fa-4119-8037-96bb147c84a6)
It seems like the problem of the apex.I have try 0.1and 0.9,but those did not work.

**Comment by dreamhonme** [comment]
您好，请问一下您怎么解决的，我这一安装apex就报错。  OSERROR

**Comment by OopsXie** [comment]
apex可以在github上找，有官方包，你下载以后导入进去。

然后我建议你在colab上运行，因为我在服务器上总报错。

colab上的操作可以查阅：https://github.com/Zyun-Y/DconnNet/issues/26

**Comment by dreamhonme** [comment]
十分感谢你提供的方法，我将会尝试一下。




L.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zyun-Y/DconnNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月22日(星期一) 晚上7:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zyun-Y/DconnNet] The version of your python apex (Issue #24)





 
apex可以在github上找，有官方包，你下载以后导入进去。
 
然后我建议你在colab上运行，因为我在服务器上总报错。
 
colab上的操作可以查阅：#26
