### ISSUE TITLE
Low Dice on CHASEDB1

### ISSUE THREAD

**Issue by AuRousKiNN** [Zyun-Y/DconnNet#32]
I attempted to train the model on the CHASEDB1 dataset, but the resulting Dice score is significantly lower than expected, at around 0.23. In contrast, using the official pretrained model for testing yields a Dice score of around 0.85.

**Environment**
- Windows 11
- Python 3.10
- PyTorch: 2.3.0+cu118 (Note: The requirement specifies torch1.7.0+cu110, which does not support RTX 40 GPUs)
- **I replaced the apex amp with PyTorch amp since I cannot install it properly**

The following arugments were used during my training (Running in PyCharm):
```
--dataset chase
--data_root ./dataset/CHASEDB1
--resize 960 960
--num-class 1
--batch-size 4
--epochs 130
--lr 0.0038
--lr-update poly
--folds 5
```

**Comment by Zyun-Y** [comment]
Would you mind sharing a screenshot of the training log and also the testing?
