### ISSUE TITLE
Questions about training time.

### ISSUE THREAD

**Issue by yiseni** [Zyun-Y/DconnNet#8]
I reproduced the model of this article and loaded my own data set for verification. There are 3,062 samples in total. The batch-size is set to 8, and it takes up to an hour to train an epoch. Is it normal? How long does it take for you to train an epoch? Thank you very much.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Zyun-Y** [comment]
May I ask what is your image size? And did you use GPU for training?
I don't remember the exact duration of training one epoch. But take Retouch as example, it takes about 5-6 hours in total to train 45 epochs.

I will double check.

**Comment by yiseni** [comment]
> May I ask what is your image size? And did you use GPU for training? I don't remember the exact duration of training one epoch. But take Retouch as example, it takes about 5-6 hours in total to train 45 epochs.
> 
> I will double check.

My data size is 640*640, and I use p100 (16g) for training. Thank you
